CREATE TABLE [dbo].[CustomerSales](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CustomerKey] [int] NOT NULL,
 CONSTRAINT [PK_CustomerSales] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[SoldBook](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[SoldBookKey] [int] NOT NULL,
	[CustomerSalesId] [int] NULL,
 CONSTRAINT [PK_SoldBook] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SoldBook]
ADD CONSTRAINT SoldBook_Fk_CustomerSales
FOREIGN KEY (CustomerSalesId)
REFERENCES CustomerSales (Id)
GO



